[workspace]
members = [
    "matrix-web-util",
    "matrix-web-test-util",
    "matrix-http-client",
    "matrix-web-dto",
    "matrix-web-entity",
    "matrix-web-model",
    "matrix-web-dao",
    "matrix-web-service",
    "matrix-web-security",
    "matrix-web-api",
]